# Generated by Django 5.1.2 on 2024-11-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("wrong1", models.TextField()),
                ("wrong2", models.TextField()),
                ("wrong3", models.TextField()),
                ("category", models.TextField()),
            ],
        ),
    ]
