# Generated by Django 5.1.2 on 2024-11-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questions",
            name="wrong1",
        ),
        migrations.RemoveField(
            model_name="questions",
            name="wrong2",
        ),
        migrations.RemoveField(
            model_name="questions",
            name="wrong3",
        ),
    ]
